### ISSUE TITLE
Active state for nav links

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#10]
Is it possible you extend this to custom navigation as well? For example, when a WooCommerce nav item is active in custom menu

Also, is it possible you make it more discrete?

For example:
1. underlined 
2. dotted
or
3. change of color (which is the most difficult one, because the background color/image may interfere)

**Comment by slobodan** [comment]
Custom navigation?

**Comment by nikolicdragan** [comment]
Sorry, meant top menue.

**Comment by slobodan** [comment]
Too complicated, what happens when social menu is used? Those get underlined too?
