### ISSUE TITLE
Widget Areas

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#14]
Something's wrong with the widget areas since WP 3.8. Some are missing. Could you inspect that?

**Comment by slobodan** [comment]
Looks OK to me. We might kill Post Top and Post Bottom for V1 though. 

![screen shot 2013-12-17 at 10 16 41 am](https://f.cloud.github.com/assets/129607/1762724/f86b7e62-66fb-11e3-8dc2-aebaecc118ab.png)
