### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#16]
1. Try to narrow down the browser windows so navigation becomes responsive. 
2. Click on the "Menu" link to expand it. 
3. Try to increase the browser window
4. The navigation disappears altogether.

**Comment by nikolicdragan** [comment]
Happens in all browsers

**Comment by slobodan** [comment]
Not an issue with latest theme version, I think from Friday or something like that.

**Comment by slobodan** [comment]
Please check.

**Comment by nikolicdragan** [comment]
Still disappears. Just updated Gumbo demo with the latest version from GitHub.

**Comment by slobodan** [comment]
You're right, sorry. I'll try to fix this although we shouldn't worry about this at all. Why would anyone do this?
