### ISSUE TITLE
Post Navigation

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#17]
1. Is it possible that when featured image is not set, post navigation takes images from within posts?
2. An option to turn off images in post navigation would be more than welcome.

**Comment by slobodan** [comment]
1. No, because then it's not featured image, it's "some image" they may or may not want shown here.
2. No need for such option. We either kill the image complete or leave it as it is.

Thoughts?

**Comment by nikolicdragan** [comment]
None.. let's leave it as it is.
