### ISSUE TITLE
Post Navigation Issue

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#18]
When I'm viewing the latest post, I still see it in the post navigation. The latest post is "sticky", so maybe that has to do something with the issue.

![post-navigation-issue](https://f.cloud.github.com/assets/2678265/1758045/207d24dc-6689-11e3-8fe0-95cae07fb0f8.png)

**Comment by slobodan** [comment]
Not a bug, previous and next posts are the ones published right before and after current post you're viewing. So, even though a sticky post appears first in homepage it's not the last one that was published. Check Posts > All Posts to confirm this. Closing the issue.

**Comment by nikolicdragan** [comment]
I still don't understand this.

Why do I see the current post (post I'm looking at) in post navigation?
