### ISSUE TITLE
Post Format Video

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#19]
Something's wrong with it. http://gumbotheme.com/category/post-formats/page/2/ (scroll down)

It doesn't show post title and when I try to create new video post format I don't get that option.

![post-format-video](https://f.cloud.github.com/assets/2678265/1758203/e70fe0c4-668b-11e3-959d-ffd4679ac49b.png)

**Comment by slobodan** [comment]
It doesn't show the title on purpose. Fixed missing video format radio button.
