### ISSUE TITLE
Comments & Trackbacks

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#2]
Is it possible these get turned off by default for Pages? (or is it a good idea, at all?)

![comments-trackbacks](https://f.cloud.github.com/assets/2678265/1713451/166cd3f0-618b-11e3-934c-e867aac1a1d0.png)

**Comment by slobodan** [comment]
It is a good idea. Need to look into this.

**Comment by slobodan** [comment]
Decided against this, don't want to alter default behaviour. We both hate comments/trackbacks in pages, but that's no reason to change it.

**Comment by nikolicdragan** [comment]
OK
