### ISSUE TITLE
Hover, active menu item state

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#22]
We should consider switching to underlining active, hover states for links. Altering colors doesn't work well.

Light color schemes & Dark color scheme experience this issue, alike.

**Comment by slobodan** [comment]
This is only for third header layout?

**Comment by nikolicdragan** [comment]
Yes, I've experienced it only on the header layout No. 3. 

It's so easy to screw colors.

**Comment by slobodan** [comment]
![screen shot 2013-12-18 at 9 51 22 am](https://f.cloud.github.com/assets/129607/1771764/988af4ac-67c1-11e3-988a-6fa4c744d844.png)
