### ISSUE TITLE
Menu item attribute

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#23]
Can't seem to make them show. They're there, just not visible.

![menu-attribute](https://f.cloud.github.com/assets/2678265/1760448/577f4e2a-66b0-11e3-8181-f818d1c1a158.png)

**Comment by slobodan** [comment]
Should be description, not Title Attribute.

![enable-menu-descriptions](https://f.cloud.github.com/assets/129607/1761777/462c7054-66dc-11e3-9c33-8a051d6e2028.jpeg)
