### ISSUE TITLE
Header text color, clear button sets it to primary color

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#24]
When you clear custom header text color, can we make it reset to primary color?

**Comment by slobodan** [comment]
Header text or header background? Header text color shouldn't be like primary color, it's most likely to be white.

But I don't think we should do this anyway, because it gets complicated easily. Three color schemes, so three defaults to reset to. Thoughts?

**Comment by nikolicdragan** [comment]
Nothing to change, then, until we hear from the customers.
