### ISSUE TITLE
WP_stats smiley

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#28]
![wordpress-stats-smiley](https://f.cloud.github.com/assets/2678265/1772288/4c358a10-67ce-11e3-837a-26ee8c47cc89.png)

appears in FF & IE

**Comment by slobodan** [comment]
Just removed it about an hour ago, try latest code.

**Comment by slobodan** [comment]
https://github.com/slobodan/Gumbo/commit/3b9e40ac8ba1068b937b4e586a42912b8f99492a

**Comment by nikolicdragan** [comment]
Great
