### ISSUE TITLE
Navigation (Responsiveness)

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#3]
![gumbo-responsiveness-issue](https://f.cloud.github.com/assets/2678265/1733247/1e5d233a-6334-11e3-8994-38a2ce224126.png)
1. active & visited links messed up
2. small margin between title & menu
3. "menu" text color

**Comment by slobodan** [comment]
What's up with the light gray bakckground? Like that on purpose?

**Comment by nikolicdragan** [comment]
1. that too, I think there's no need to make it lighter or put any other background color
