### ISSUE TITLE
Customizer issue in IE

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#30]
IE 11, Can't select any of the layouts. I click, but it wont select. How should we test this?

![customizer-issue](https://f.cloud.github.com/assets/2678265/1772717/ebd0ed50-67d6-11e3-99c5-b0952c3b323c.jpg)

**Comment by nikolicdragan** [comment]
OK.. it works, but I have to click 5px below layout icon in order to select it.

**Comment by nikolicdragan** [comment]
For everything else, IE works good in Customizer.

**Comment by slobodan** [comment]
Fu*k. I'll look into it, might need to revert to radio buttons till I figure it out.
