### ISSUE TITLE
Post Formats

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#31]
http://gumbotheme.com/post-format-status/ Status wasn't CSS-ed. How about we add some underlining?

http://gumbotheme.com/post-format-quote/ Make it bigger than a standard quote?

..

**Comment by slobodan** [comment]
That's not how post formats work, when seeing a single post they are all shown as standard posts. They look different in archives.

**Comment by nikolicdragan** [comment]
Super
