### ISSUE TITLE
Sitemap template

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#33]
Something's wrong with it. http://gumbotheme.com/page-templates/sitemap/
1. It's not in 3 columns
2. Can't get rid of the comments on this page

**Comment by slobodan** [comment]
It shouldn't be three columns (that was 404 page), one of the columns would be much longer than the other two.

**Comment by slobodan** [comment]
Actually, there would need to be more than 3 columns, since it shows custom posts as well.
