### ISSUE TITLE
404 template

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#35]
How about we insert 404 genericon on 404 template?

Somewhere in the upper part in the middle?

**Comment by slobodan** [comment]
404 genericon?

http://genericons.com/

Don't see it

**Comment by nikolicdragan** [comment]
Sorry, I saw it here and thought it was part of genericons

![genericons](https://f.cloud.github.com/assets/2678265/1781971/cae36828-68a0-11e3-8aa8-5aa5275be4f2.png)

**Comment by slobodan** [comment]
Mystery...
