### ISSUE TITLE
Widgetized page

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#36]
1. It's still called "Widegetized Homepage" in Appearance > Widgets
2. Why is this called "Authors Page"? I forgot... Maybe it can be called "Page Settings"?
   ![widgetized-page-template](https://f.cloud.github.com/assets/2678265/1777082/ac05fd84-681f-11e3-9f35-c8ae7bf8590f.png)

**Comment by slobodan** [comment]
My mistake on "Authors Page", corrected.
