### ISSUE TITLE
Next Gumb Masonry

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#38]
![next-gumb-masonry](https://f.cloud.github.com/assets/2678265/1777249/0450a48c-6823-11e3-8539-9e370a9de1f5.png)

**Comment by nikolicdragan** [comment]
Check pagination.. thanks.

![pagination-masonry-issue](https://f.cloud.github.com/assets/2678265/1777269/3b298faa-6823-11e3-8152-5a21e0797006.png)

**Comment by slobodan** [comment]
Fixed this yesterday.

**Comment by slobodan** [comment]
Check with latest version
