### ISSUE TITLE
Left Slider Arrow

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#39]
Something above the left arrow in IE

![left-arrow](https://f.cloud.github.com/assets/2678265/1782845/d809190a-68b7-11e3-9b21-d81bbe29c3b8.png)

**Comment by slobodan** [comment]
Can you check again, with latest? It had text-decoration: underline.

**Comment by nikolicdragan** [comment]
It's OK now.

I don't think we need arrows and dots for slider. It's redundant, right?

I vote for dots.. don't tell me it's going to be a tie :)

**Comment by slobodan** [comment]
Dots.
