### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#4]
The titles of widget areas are not that clear to me. Why use "widget area" in title, since this section is for widgets?
![gumbo-widgets](https://f.cloud.github.com/assets/2678265/1733856/eaf44442-633d-11e3-8f52-1da4c6308972.png)

**Comment by slobodan** [comment]
Just remove "Widget Area" in all of these?

**Comment by nikolicdragan** [comment]
Correct
