### ISSUE TITLE
Navigation responsiveness

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#40]
Nav disappears altogether when browser window around 610px.

**Comment by slobodan** [comment]
Are you 100% sure this happens? Breakpoint is at 600px, there's nothing that changes the menu at 610px.

**Comment by nikolicdragan** [comment]
The latest version of Gumbo. Just shrink browser windows slowly.

![ie-menu-issue](https://f.cloud.github.com/assets/2678265/1789980/1e62e75e-6968-11e3-8e73-c71ed4aef217.png)
606px wide

![chrome-menu-issue](https://f.cloud.github.com/assets/2678265/1789981/2151046e-6968-11e3-9368-d9aae17c0fd3.jpg)
605px wide
