### ISSUE TITLE
Social Menu (google+)

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#41]
Can't seem to get it to work (what URL do I have to use?)

I used 
https://plus.google.com/+Thematosoup/posts
https://www.google.com/+Thematosoup

**Comment by nikolicdragan** [comment]
Which networks are supported?

**Comment by slobodan** [comment]
Check Trello card, there's a ist there

---

_Slobodan Manic_
@ http://twitter.com/slobodanmanicslobodanmanichttp://twitter.com/slobodanmanic

**Comment by slobodan** [comment]
Since when is Google+ URL www.google.com? :)

**Comment by slobodan** [comment]
https://www.google.com/+Thematosoup
