### ISSUE TITLE
Menu item without description + item with description

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#43]
If you can tweak the hover/active state of the item that has no description, so it's same as items that do have.

![menu-without-description](https://f.cloud.github.com/assets/2678265/1792169/6c642ce2-699a-11e3-97d9-288be1c65024.png)

**Comment by slobodan** [comment]
I'll try to come up with something but this is very complicated, since those two menu items have different height. The idea is to either use description in all of them, or not use it at all.

**Comment by nikolicdragan** [comment]
No need.. I completely agree that if one chooses to use description for menu items, she/he should use them on all of them.
