### ISSUE TITLE
Widgetized Page

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#44]
Can we make text wrap around the featured image/video?

I think it would be useful.

![widgetized page](https://f.cloud.github.com/assets/2678265/1795972/7ccfd9d8-6a48-11e3-89cc-ba01c21ccdbd.png)

**Comment by slobodan** [comment]
I don't think that would look good.

If text is barely longer than picture and you want it on the side, it would look really bad.

If text is much longer you can still make it look good by placing it below the photo/video.

**Comment by nikolicdragan** [comment]
Why would you want it on the side if it was barely longer than the photo/video? When did you want ever want that?

**Comment by nikolicdragan** [comment]
This is not a portfolio item

**Comment by slobodan** [comment]
I don't understand, what does portfolio item have to do with anything?

**Comment by nikolicdragan** [comment]
I just thought that it might be good for portfolio items not to have text wrap around images, but not here.

**Comment by slobodan** [comment]
So, the idea is to use it on the side if text is shorter, and below/above if text is longer than media. No need to change anything, in my opinion.

**Comment by nikolicdragan** [comment]
Alright
