### ISSUE TITLE
Vimeo video

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#46]
![vimeo-embed](https://f.cloud.github.com/assets/2678265/1797747/2b5bca68-6b0a-11e3-954f-3849fcecadac.jpg)

The black stripe doesn't appear on youtube videos, just vimeo. Is that how WordPress embeds vimeo videos or is it something we can do about it?

http://gumbotheme.com/page-templates/widgetized/landing-page-text-top/

**Comment by nikolicdragan** [comment]
BTW, widgetized pages demos aren't done.. Will look much better.

**Comment by slobodan** [comment]
Has to do with embed width/height, I'll see what we can do.
