### ISSUE TITLE
Featured content changes

### ISSUE THREAD

**Issue by slobodan** [ThematoSoup/Gumbo#47]
I added one more Customizer option to featured content area: Featured Content Width. Options are full width and content width.

![screen shot 2013-12-23 at 10 57 50 am](https://f.cloud.github.com/assets/129607/1800084/bd6bdd9a-6bb8-11e3-95e0-53996c2e4f33.png)
![screen shot 2013-12-23 at 10 58 05 am](https://f.cloud.github.com/assets/129607/1800085/bd6dacd8-6bb8-11e3-9bea-beef48dabcb7.png)

**Comment by slobodan** [comment]
This is just info, you can close or delete the ticket when you see it and add to documentation.

**Comment by nikolicdragan** [comment]
awesome
