### ISSUE TITLE
Tiled gallery - JeztPacket

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#49]
http://gumbotheme.com/tiled-gallery/
1. No Sidebar layout is selected, but it looks this post format is not using full width.
2. When you click on an image (in IE11) it looks like this (image appears aligned right)
   ![jetpack gallery](https://f.cloud.github.com/assets/2678265/1818035/d2112920-6fd8-11e3-8719-66a9e51d2399.jpg)

**Comment by slobodan** [comment]
Can you test the one here as well? 

http://jetpack.me/support/carousel/

(scroll down)

**Comment by nikolicdragan** [comment]
Same problem, so it's something to do with Jetpacks' module, not Gumbo.

Closing issue.
