### ISSUE TITLE
Expand image button in WooCommerce shop

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#50]
Click on the expand image button on any shop item. It becomes barely visible after the image expands.

Is this something we can fix, or is this WooCommerce issue?

![expand-image-button-woocommerce-shop](https://f.cloud.github.com/assets/2678265/1818132/36863540-6fe2-11e3-889d-80430756b176.jpg)

**Comment by slobodan** [comment]
It's how the lightbox script used by WooCommerce works. I'd leave this one as it is for now.
