### ISSUE TITLE
Widgetized Template, widget issues

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#57]
http://gumbotheme.com/page-templates/widgetized/
1. When I try to add a widget in one of the child pages, the 6 widgets on the parent page (http://gumbotheme.com/page-templates/widgetized/) take 4-2 formation, instead of 3-3.
2. This happens also when I try to add a widget in the Above Footer widget area, which is the case now. The banner in the Above Footer area somehow makes widgets in widgetized template misbehave.

**Comment by slobodan** [comment]
@nikolicdragan How do you add widgets to child pages? Jetpack widget visibility?

**Comment by slobodan** [comment]
I think it's better to create a new sidebar using a sidebar manager plugin (like Woo Sidebars, it's called something like that) and then have a dropdown in Widgetized template meta box, to select a sidebar.

@nikolicdragan thoughts?

**Comment by nikolicdragan** [comment]
Probably right. Seems like Jetpack's Visibility module has issues with child pages.

I'll the method you've mentioned.

**Comment by slobodan** [comment]
I need to change the template a bit to add sidebar select option. We're
definitely going with that, right?

Need to recommend a plugin for it in documentation and demo then.

---

_Slobodan Manic_
@ http://twitter.com/slobodanmanicslobodanmanichttp://twitter.com/slobodanmanic

**Comment by nikolicdragan** [comment]
Yes
