### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#6]
If you can make it similar to what's on http://thematosoup.com/blog/ (for example)

**Comment by slobodan** [comment]
Isn't it similar already?

![screen shot 2013-12-16 at 8 29 11 am](https://f.cloud.github.com/assets/129607/1752563/cc066c16-6623-11e3-80f9-42849e639ba5.png)

**Comment by nikolicdragan** [comment]
Looks too generic to me.

**Comment by slobodan** [comment]
Increase height.
