### ISSUE TITLE
Menu Responsieveness issue

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#60]
Doesn't work.
![menu-responsiveness](https://f.cloud.github.com/assets/2678265/1905966/1b723c64-7ca7-11e3-9d27-3274d106d600.jpg)

**Comment by slobodan** [comment]
@nikolicdragan cause you broke it :)

Had to do with JS minify settings in W3TC, fixed now.

**Comment by nikolicdragan** [comment]
Oh right.. sorry. I forgot about possible issues with minification :)

**Comment by slobodan** [comment]
All good now, I fixed the settings.

---

_Slobodan Manic_
@ http://twitter.com/slobodanmanicslobodanmanichttp://twitter.com/slobodanmanic
