### ISSUE TITLE
Post Format Gallery (archive)

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#67]
http://gumbotheme.com/page/3/

Images look blurred when blog view set to "no sidebars" (full width).

Something we can do about this?

**Comment by nikolicdragan** [comment]
Also tiled gallery doesn't use the whole width (when no sidebars layout is set)

Once you open it it's OK, but in blog archive, it's not using entire width. No options for this in Jetpack's Tiled Gallery module.

**Comment by nikolicdragan** [comment]
The blurriness disappears once you set Media > Image Gallery Carousel > Tiled Galleries -
 Display all your gallery pictures in a cool mosaic.

When it's turned off, images appear blurred.

**Comment by slobodan** [comment]
Can you try tiled gallery and full width again, works for me locally. I made some changes to this last week.

I don't understand the problem with blurred images. I guess if thumbnails in gallery are larger than what thumbnail size is set to in Settings > Media they have to be blurred.

**Comment by nikolicdragan** [comment]
So what do we do with this?

**Comment by nikolicdragan** [comment]
Does this happen to you too?

**Comment by slobodan** [comment]
I think this is because thumbs are 150x150 and here they are displayed in 195x195, will resize thumbs to see if that helps

**Comment by slobodan** [comment]
That was it.

**Comment by nikolicdragan** [comment]
Ok great
