### ISSUE TITLE
Infite scroll issue

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#69]
![infinite-scroll-issue](https://f.cloud.github.com/assets/2678265/1944489/070d806e-7fbb-11e3-89ab-7b38e7e82654.png)

I just don't understand what footer widgets have to do with infinite scroll?

**Comment by nikolicdragan** [comment]
I've tried removing footer widgets, but infinite scroll didn't work, so it must be something else.

**Comment by slobodan** [comment]
http://jetpack.me/support/infinite-scroll/

Breaking down each option:

_type_
type accepts two different values: scroll or click. This controls the default Infinite Scroll behaviour. scroll will cause posts to be loaded automatically when the visitor approaches the bottom of the current list of posts, while click shows a Load more posts button, letting the user control when more posts are loaded.

scroll is the default, but if a theme has footer widgets, this could be overridden to click so the widgets are accessible.

**Comment by slobodan** [comment]
It's set to click in Gumbo, because of footer widgets.

**Comment by nikolicdragan** [comment]
Sorry, my bad.. totally neglected the click value.
