### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#70]
When enabled, the last page in the breadcrumb is slightly bold, although there's an option for that in WordPress SEO plugin.

![breadcrumbs](https://f.cloud.github.com/assets/2678265/1945410/e535306a-7fcc-11e3-80ba-fe9b73127f59.png)

Can we make it not bold at all?

**Comment by slobodan** [comment]
That's not bold, it's darker text because it's not a link. All meta links in the theme are gray. Here it is with bold activated. I'd leave this one as is.

![screen shot 2014-01-20 at 9 42 16 am](https://f.cloud.github.com/assets/129607/1952729/cdfa1b98-81ae-11e3-8dc3-e891b451d275.png)

**Comment by nikolicdragan** [comment]
Agreed.
