### ISSUE TITLE
Font Size impacts all text, not just post/page text

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#72]
Take a look at this page which has font size set to "large" http://gumbotheme.com/contact/

The Title, site description, footer....everything is also larger than normal. Is this the desired behavior?

**Comment by slobodan** [comment]
Yes

---

_Slobodan Manic_
@ http://twitter.com/slobodanmanicslobodanmanichttp://twitter.com/slobodanmanic

**Comment by nikolicdragan** [comment]
thanks
