### ISSUE TITLE
Gumbo description

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#74]
![2014-description](https://f.cloud.github.com/assets/2678265/1975076/8bf54d0a-8378-11e3-8ffd-8e92e23c116b.jpg)

For Gumbo:

Gumbo is an extremely flexible WordPress theme easy to setup and customize. It’s created with two things in mind:
- WordPress best practices
- Minimalism

If you’re looking for a premium responsive WordPress theme that focuses on your content, the ease of use and customer support, you’re in the right spot.
Gumbo is using all the latest WordPress standards so it’s:
- Stable
- Secure
- Optimized
- Future proof

**Comment by slobodan** [comment]
I don't think lists can be used here, but good point, we forgot about this.
Adding in 5 min.

---

_Slobodan Manic_
@ http://twitter.com/slobodanmanicslobodanmanichttp://twitter.com/slobodanmanic
