### ISSUE TITLE
Widgetized page responsiveness

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#75]
How about me make image/video appear above the text.. we get larger image/video and a more readable text.

![widgetized-responsiveness](https://f.cloud.github.com/assets/2678265/1982371/94aa00a8-83fa-11e3-95ba-08d2c019aab5.png)

**Comment by slobodan** [comment]
Makes sense

---

_Slobodan Manic_
@ http://twitter.com/slobodanmanicslobodanmanichttp://twitter.com/slobodanmanic
