### ISSUE TITLE
Post navigation

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#79]
Post titles should maybe take primary color. What do you think?

**Comment by slobodan** [comment]
No, looks really bad, they should be the same color as headings.

---

_Slobodan Manic_
@ http://twitter.com/slobodanmanicslobodanmanichttp://twitter.com/slobodanmanic

**Comment by slobodan** [comment]
Ignore previous comment, I thought you meant main post titles. Regardless, I think it's better to leave these as they are.

**Comment by slobodan** [comment]
Added the images back btw.

**Comment by slobodan** [comment]
![screen shot 2014-01-27 at 1 49 56 pm](https://f.cloud.github.com/assets/129607/2008778/8efbcc36-8751-11e3-8b56-9549a2537294.png)
![screen shot 2014-01-27 at 1 49 46 pm](https://f.cloud.github.com/assets/129607/2008779/8f134cb2-8751-11e3-9095-647dff13f670.png)

**Comment by nikolicdragan** [comment]
OK, awesome
