### ISSUE TITLE
Removal of footer action in child theme

### ISSUE THREAD

**Issue by kdbruin** [ThematoSoup/Gumbo#90]
Hi, the code to remove the Gumbo footer in the child theme's functions.php is incorrect. The correct code is:

``` php
/**
 * Update hooks and actions
 */
function child_update_actions() {
    remove_action( 'gumbo_credits', 'gumbo_footer_credits', 10 );
}
add_action( 'init', 'child_update_actions' );
```

**Comment by slobodan** [comment]
Hi @kdbruin,

What's wrong with just remove_action? Works fine.

**Comment by kdbruin** [comment]
As Gumbo's functions.php is processed after a child's functions.php the action would be added again. I've tried your code and it didn't remove the footer. After some Googling I found the above solution and it works.

**Comment by slobodan** [comment]
Got it and you're correct. I only tested this from parent theme's function.php.

Thanks for reporting the issue!
